/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class me_xiaoying_logger_JNILogger */

#ifndef _Included_me_xiaoying_logger_JNILogger
#define _Included_me_xiaoying_logger_JNILogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_xiaoying_logger_JNILogger
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_xiaoying_logger_JNILogger_send
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
